// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WardrobeManagerAPI.Data;

#nullable disable

namespace WardrobeManagerAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221117183930_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WardrobeManagerAPI.Entities.Wardrobe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Wardrobes");
                });

            modelBuilder.Entity("WardrobeManagerAPI.Entities.WardrobeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WardrobeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WardrobeId");

                    b.ToTable("WardrobeItems");
                });

            modelBuilder.Entity("WardrobeManagerAPI.Entities.WardrobeItem", b =>
                {
                    b.HasOne("WardrobeManagerAPI.Entities.Wardrobe", null)
                        .WithMany("Items")
                        .HasForeignKey("WardrobeId");
                });

            modelBuilder.Entity("WardrobeManagerAPI.Entities.Wardrobe", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
